services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dondong-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
